### PR TITLE
ESP8266 Support

### PR DESCRIPTION
**Pull request by mrbig**
Hi, 
I've added esp8266 support to your great project. Android-core for esp8266 does not have SREG support, but has an alternative for that. See: https://github.com/esp8266/Arduino/issues/615

Could you please review my changes and pull them if you find it appropriate?

### CODE REVIEW

**Comment by igormiktor** [comment]
Hi,

Thanks for providing this.  I've also been asked to adapt interrupts to support SAM microcontrollers (Arduino Due).  So I decided to refactor the interrupt handling code into a separate class.  I've put this all in a new branch, "mrbig-esp8266_support".  Can I trouble you to please checkout this branch and make sure it works on the esp8266.

One favor:  your check for esp8266 seems to check for a header file (I'm guessing that is what ESP_H is).  Instead, is there a pre-defined compiler macro indicating we are compiling for ep8266?  It would be much more reliable to check for that instead of a specific header file.  The checks for AVR and SAM microcontrollers are based on official gcc pre-defined macros, defined only when compiling for those hardware architectures.

Let me know if this all works, and I'll merge it into master.

Thanks,
Igor

**Comment by mrbig** [comment]
Hi, I've updated the macro definition, I just didn't find the right one until now.

You're code compiles nicely, I'll be testing it out later today. As I see you found a bug in my code, thanks for fixing it!

**Comment by igormiktor** [comment]
Excellent -- that's a more reliable macro.  I don't have an esp8266, so let me know once you have a successful test and I'll merge.

Thanks again!

**Comment by mrbig** [comment]
Hi,
It's been running flawlessly for ~48 hours on my device, so it seems to be stable to me.

**Comment by igormiktor** [comment]
Great to hear.  I just merged.  Thanks so much for your help.

**Pull request merged**
